# Generated by Django 5.2.1 on 2025-06-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('report_type', models.CharField(choices=[('appointments', 'Appointments Report'), ('revenue', 'Revenue Report'), ('staff_performance', 'Staff Performance'), ('client_analysis', 'Client Analysis'), ('service_popularity', 'Service Popularity'), ('feedback_summary', 'Feedback Summary')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(default=dict)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule_frequency', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='KPIMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('name', 'date', 'category')},
            },
        ),
    ]
